version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: biogenom
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  webapi:
    build:
      context: .
      dockerfile: Biogenom.WebApi/Dockerfile
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=8080;Database=biogenom;Username=postgres;Password=postgres
    ports:
      - "8080:80"
    command: ["sh", "-c", "sleep 10 && dotnet Biogenom.WebApi.dll"]


volumes:
  pgdata: